version: "3"
services:
  backend:
    container_name: rails-backend
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:3000"
    env_file:
      - ./config.env
    networks:
      - boggle

  frontend:
    container_name: react-frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:80"
    depends_on:
      - backend
    env_file:
      - ./config.env
    networks:
      - boggle

networks:
  boggle:
    driver: bridge
