version: "3"
services:
  backend:
    container_name: rails-backend
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    env_file:
      - ./config.env
    networks:
      - boggle

  frontend:
    container_name: react-frontend
    build: ./frontend
    # command: bash -c "nginx -g daemon off;"
    volumes:
      - ./frontend:/app
    ports:
      - "8080:80"
    depends_on:
      - backend
    env_file:
      - ./config.env
    networks:
      - boggle

networks:
  boggle:
    driver: bridge
