export const INITIALIZE_GAME = "INITIALIZE_GAME";
export const SET_USER_INPUT = "SET_USER_INPUT";
export const SUBMIT_CORRECT_WORDS = "SUBMIT_CORRECT_WORDS";
export const UPDATE_TIMER = "UPDATE_TIMER";
export const RESET_TIMER = "RESET_TIMER";
export const SET_TIMER_OBJECT = "SET_TIMER_OBJECT";
export const START_GAME_INITIALIZATION = "START_GAME_INITIALIZATION";
export const RESET_SCORE_BOARD = "RESET_SCORE_BOARD";
